name: Build & Deploy

on:
  push:
    branches: ['main']

  # webhook trigger, contentful calls it whenever something is published
  repository_dispatch:
    types: [publish-event]        

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.17.6']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run npm build
        env:
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}  
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir is the folder on the docker instance which eleventy builds the pages to
          publish_dir: _site
          # publish_branch is the branch in the repository
          # this is where you need to point GitHub pages
          publish_branch: gh-pages